export const AUTHENTICATION_SIGN_IN = 'AUTHENTICATION_SIGN_IN';
export const AUTHENTICATION_SIGN_UP = 'AUTHENTICATION_SIGN_UP';
export const AUTHENTICATION_SIGN_OUT = 'AUTHENTICATION_SIGN_OUT';
export const AUTHENTICATION_SET_USERNAME = 'AUTHENTICATION_SET_USERNAME';
